name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '22'

jobs:
  backend:
    name: Backend (Lint & Build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint backend
        run: yarn workspace backend lint

      - name: Build backend
        run: yarn workspace backend build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: apps/backend/dist
          retention-days: 1

  frontend:
    name: Frontend (Lint & Build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint frontend
        run: yarn workspace frontend lint

      - name: Build frontend
        run: yarn workspace frontend build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: apps/frontend/dist
          retention-days: 1

  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    if: always()
    steps:
      - name: Check all jobs
        run: |
          if [ "${{ needs.backend.result }}" != "success" ] || \
             [ "${{ needs.frontend.result }}" != "success" ]; then
            echo "One or more jobs failed"
            exit 1
          fi
          echo "All CI jobs passed successfully"
