# Dockerfile pour le développement
FROM node:22.16.0-alpine3.22

WORKDIR /app

COPY package.json yarn.lock ./
COPY apps/backend/package.json ./apps/backend/
COPY apps/frontend/package.json ./apps/frontend/

RUN yarn install --frozen-lockfile

# Le reste sera monté via volume dans docker-compose.yml
CMD ["sleep", "infinity"]

